# Generated by Django 3.2.4 on 2023-04-03 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20230330_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcategory',
            name='logo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('1', 'MONTHLY'), ('3', 'QUARTER'), ('6', 'HALF-YEARLY'), ('C', 'YEARLY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptiondetail',
            name='status',
            field=models.CharField(choices=[('A', 'ACTIVE'), ('C', 'CANCELLED'), ('E', 'EXPIRED')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='admins',
            field=models.ManyToManyField(null=True, related_name='tenants', to='account.TenantUser'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
