version: '3.2'
services:
  web:
    build: .
    container_name: planny-local
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      DB_URL_PRODUCTION: postgres
      DB_NAME: planny
      DB_USER: planny
      DB_PASSWORD: password
    profiles:
      - local
    ports:
      - '8000:8000'

  postgres:
    image: postgres:13-alpine
    container_name: planny-postgres
    environment:
      POSTGRES_USER: planny
      POSTGRES_DB: planny
      POSTGRES_PASSWORD: password
    profiles:
      - local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planny"] # Adjust the username as per your PostgreSQL setup
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
