version: '3.2'
services:
  web:
    build: .
    container_name: phurti-local
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    env_file: .env
    environment:
      DB_URL_PRODUCTION: postgres
      DB_NAME: phurti
      DB_USER: phurti
      DB_PASSWORD: password
    profiles:
      - local
    ports:
      - '8000:8000'

  postgres:
    image: postgres:13-alpine
    container_name: phurti-postgres
    environment:
      POSTGRES_USER: phurti
      POSTGRES_DB: phurti
      POSTGRES_PASSWORD: password
    profiles:
      - local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U phurti']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
