# Generated by Django 3.2.4 on 2023-03-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name')),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Mobile Number')),
                ('address', models.TextField(default='')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[('PHONE_NUMBER', 'PHONE_NUMBER'), ('EMAIL', 'EMAIL'), ('ADDRESS', 'ADDRESS')], default=1, verbose_name='Alternative Type')),
                ('value', models.CharField(db_index=True, max_length=255, verbose_name='Email or Phone')),
                ('primary', models.BooleanField(default=False, verbose_name='Is Primary?')),
                ('verified', models.BooleanField(default=False, verbose_name='Is Verified?')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('label', models.CharField(blank=True, choices=[('Home', 'Home'), ('Office', 'Office'), ('Others', 'Others')], max_length=255, null=True, verbose_name='label')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
