ROLE = (
    ("C", ("CUSTOMER")),
    ("DP", ("DELIVERYPARTNER")),
    ("SK", ("STOREMANAGER")),
    ("ADMIN", ("ADMIN")),
)
CREDIT = "CREDIT"
DEBIT = "DEBIT"
SUCCESS = "SUCCESS"
FAILED = "FAILED"

TRANSACTION_TYPES = ((CREDIT, CREDIT), (DEBIT, DEBIT))
STAFF_CATEGORY = (("C", "CONTRACTOR"), ("D", "DRIVER"))
