SUCCESS = "SUCCESS"
FAILED = "FAILED"
COD = "cash_on_delivery"
ECOD = "electronic_cash_on_Delivery"
QRCODE = "qr_code"
RAZORPAY = "razorpay"
UPI = "upi"
CASH = "cash"
NETBANKING = "netbanking"
WEBSITE = "website"
SUCCESS = "SUCCESS"
FAILED = "FAILED"
CHECKOUT = "CHECKOUT"
PAYMENT_SUCCESS = "PAYMENT_SUCCESS"
PAYMENT_FAILED = "PAYMENT_FAILED"
OFFLINE = "offline"


# NUMERIC CONSTANTS
ZERO = 0
ONE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE = 5
SIX = 6
TEN = 10
TWENTY = 20
FIFTY = 50
HUNDRED = 100
TWO_HUNDRED = 200
FIFTY_THOUSANDS = 50000


