# Generated by Django 3.2.4 on 2023-04-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230403_1446'),
        ('shop', '0003_alter_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.JSONField(default={'state_list': [{'action': None, 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': 'Welcome to Aikam\nNow get your medicines at your doorstep with huge discount'}, 'created_on': 'April 2023, 14:46PM', 'sender': 'AIKAM', 'state_type': 'TEXT'}, {'action': 'REQUEST_CALLBACK', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'April 2023, 14:46PM', 'sender': 'AIKAM', 'state_type': 'REQUEST_CALLBACK'}, {'action': 'UPLOAD_PRESCRIPTION', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'April 2023, 14:46PM', 'sender': 'AIKAM', 'state_type': 'UPLOAD_PRESCRIPTION'}]}),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='account.tenant'),
        ),
    ]
