# Generated by Django 3.2.4 on 2023-04-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230407_1149'),
        ('shop', '0005_alter_order_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
                ('price_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productpricevariation')),
            ],
            options={
                'verbose_name_plural': 'ProductVariation',
            },
        ),
        migrations.CreateModel(
            name='VariationTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='variation_types', verbose_name='Variation Image')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'VariationTypes',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='has_variation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellableinventory',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.JSONField(default={'state_list': [{'action': None, 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': 'Welcome to Aikam\nNow get your medicines at your doorstep with huge discount'}, 'created_on': 'April 2023, 18:00PM', 'sender': 'AIKAM', 'state_type': 'TEXT'}, {'action': 'REQUEST_CALLBACK', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'April 2023, 18:00PM', 'sender': 'AIKAM', 'state_type': 'REQUEST_CALLBACK'}, {'action': 'UPLOAD_PRESCRIPTION', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'April 2023, 18:00PM', 'sender': 'AIKAM', 'state_type': 'UPLOAD_PRESCRIPTION'}]}),
        ),
        migrations.CreateModel(
            name='VariationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('variation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variationtypes')),
            ],
            options={
                'verbose_name_plural': 'VariationOptions',
            },
        ),
        migrations.CreateModel(
            name='VariationCombos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariation')),
                ('variation_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variationoptions')),
            ],
            options={
                'verbose_name_plural': 'VariationCombos',
            },
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
