# Generated by Django 3.2.4 on 2023-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20230501_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cap_on_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hsn_codes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='channel_invoice_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='channel_invoice_number',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='hsn_code',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.JSONField(default={'state_list': [{'action': None, 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': 'Welcome to Aikam\nNow get your medicines at your doorstep with huge discount'}, 'created_on': 'May 2023, 18:34PM', 'sender': 'AIKAM', 'state_type': 'TEXT'}, {'action': 'REQUEST_CALLBACK', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'May 2023, 18:34PM', 'sender': 'AIKAM', 'state_type': 'REQUEST_CALLBACK'}, {'action': 'UPLOAD_PRESCRIPTION', 'body': {'media_height': None, 'media_width': None, 'thumbnail_image': {'height': None, 'url': None, 'width': None}, 'value': None}, 'created_on': 'May 2023, 18:34PM', 'sender': 'AIKAM', 'state_type': 'UPLOAD_PRESCRIPTION'}]}),
        ),
    ]
