# Generated by Django 3.2.4 on 2023-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('license_number', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
