# Generated by Django 3.2.4 on 2023-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
